import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseKey)

const seeds: { category_id: number; title: string; body: string }[] = [
  // ===== Windows & Computers (1-20) =====
  { category_id: 1, title: 'إزاي أحل مشكلة بطء ويندوز 11 بعد التحديث؟', body: 'بعد آخر تحديث لويندوز 11 صار جهازي تقيل جداً. البرامج بتفتح ببطء والجهاز بيعلق كتير.\n\nالحل:\n1. افتح Task Manager (Ctrl + Shift + Esc)\n2. افحص البرامج اللي بتستهلك موارد عالية\n3. عطل برامج Startup غير الضرورية\n4. شغّل Disk Cleanup\n5. جرب تعطيل تأثيرات الأداء: Settings > Performance > Adjust for best performance\n6. لو المشكلة مستمرة، ارجع التحديث: Settings > Windows Update > Update history > Uninstall updates' },
  { category_id: 1, title: 'ازاي أعمل فورمات للابتوب من غير ما أضيع ملفاتي؟', body: 'عايز أعمل فورمات للابتوب بس خايف أضيع الملفات المهمة.\n\nالحل:\n1. اعمل Backup على هارد خارجي أو OneDrive\n2. استخدم Reset this PC: Settings > System > Recovery > Reset PC\n3. اختر "Keep my files"\n4. إختار "Cloud download" عشان تثبيت نسخة نظيفة\n5. بعد الفورمات، هتلاقي ملفاتك في مجلد Windows.old' },
  { category_id: 1, title: 'مشكلة الشاشة الزرقاء (Blue Screen) في ويندوز 10', body: 'بتظهرلي شاشة زرقاء كل شوية ورمز الخطأ IRQL_NOT_LESS_OR_EQUAL.\n\nالحل:\n1. شغّل Windows Memory Diagnostic عشان تفحص الرامات\n2. حدث درايفرات كارت الشاشة\n3. شغّل sfc /scannow في Command Prompt كـ Admin\n4. لو المشكلة مستمرة، جرب إزالة أي جهاز USB خارجي\n5. افحص الهارد ديسك: chkdsk /f في CMD' },
  { category_id: 1, title: 'إزاي أوصل طابعة على الشبكة في ويندوز 11؟', body: 'عندي طابعة HP عايز أشاركها على الشبكة عشان كل الأجهزة تطبع عليها.\n\nالحل:\n1. وصل الطابعة بالراوتر عبر USB أو Ethernet\n2. على الكمبيوتر الأساسي: Settings > Bluetooth & devices > Printers & scanners\n3. اختار الطابعة > Printer properties > Sharing\n4. فعّل "Share this printer"\n5. على الأجهزة التانية: Add printer > Add network printer' },
  { category_id: 1, title: 'حل مشكلة عدم ظهور الواي فاي في ويندوز 11', body: 'اختفى أيقونة الواي فاي من شريط المهام ومالقيتش أي شبكات.\n\nالحل:\n1. افتح Device Manager وانظر على Network adapters\n2. لو في علامة صفراء، حدث الدرايفر\n3. شغّل Network Troubleshooter: Settings > System > Troubleshoot\n4. في CMD كـ Admin: netsh winsock reset وبعدين restart\n5. لو لسه، ارجع الدرايفر لنسخة أقدم: Driver > Roll back driver' },
  { category_id: 1, title: 'إزاي أزيل باسوورد ويندوز 11 من غير ما أعمل فورمات؟', body: 'نسيت باسوورد الكمبيوتر ومش عارف أدخل.\n\nالحل:\n1. استخدم حساب Microsoft عشان تعيد تعيين الباسوورد أونلاين\n2. من شاشة الـ Login، اضغط على Reset password بعد محاولة فاشلة\n3. لو عندك USB Boot، استخدم أداة Hiren Boot أو Trinity Rescue Kit\n4. استخدم الوضع الآمن (Safe Mode) بحساب Admin المخفي\n5. للوقاية المستقبلية: اعمل Password Reset Disk' },
  { category_id: 1, title: 'مشكلة ارتفاع حرارة اللابتوب — حل نهائي', body: 'الابتوب بيسخن جداً بعد شوية استخدام وحتى المروحة بتشتغل بصوت عالي.\n\nالحل:\n1. نظف المروحة والفتحات من التراب (مفك براغي وعلبة هواء)\n2. استخدم قاعدة تبريد (Cooling Pad)\n3. غير الباور سيتنق لـ Power Saver أو Balanced\n4. افحصTask Manager وشوف إيه اللي بيستهلك CPU\n5. غير المعجون الحراري (Thermal Paste) لو عندك خبرة\n6. استخدم برنامج ThrottleStop لتحكم في سرعة المعالج' },
  { category_id: 1, title: 'ازاي أعمل Recovery USB لويندوز 11؟', body: 'عايز أعمل USB إقلاع عشان لو النظام وقع أقدر أصلحه.\n\nالحل:\n1. USB فلاشة 8 جيجا على الأقل\n2. حمل Media Creation Tool من موقع مايكروسوفت\n3. شغّل الأداة واختار "Create installation media"\n4. اختار اللغة والإصدار (Windows 11)\n5. اختار USB flash drive\n6. استنى لحد ما التحميل يخلص (30-60 دقيقة)' },
  { category_id: 1, title: 'حل مشكلة عدم فتح متجر Microsoft Store', body: 'المتجر مش عايز يفتح خالص — بيظهر رسالة خطأ أو بيقفل لوحده.\n\nالحل:\n1. شغّل WSReset.exe في Run (Windows + R)\n2. شغّل Troubleshooter: Settings > System > Troubleshoot > Windows Store Apps\n3. استخدم PowerShell كـ Admin: Get-AppXPackage *WindowsStore* | Foreach { Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml" }\n4. حدث ويندوز لآخر إصدار\n5. اعمل Restart و حاول تاني' },
  { category_id: 1, title: 'ازاي أخفي ملف أو فولدر في ويندوز من غير برامج؟', body: 'عايز أخفي ملفات معينة عشان محدش يشوفها.\n\nالحل:\n1. اختار الملف > كليك يمين > Properties\n2. فعّل Hidden > Apply\n3. من File Explorer: View > Show > uncheck Hidden items\n4. الطريقة التانية: غير اسم الملف وابدأ بنقطة (.) — ده بيخفي\n5. الطريقة الأقوى: Attrib +h +s "path" في CMD\n6. الملفات هتظهر لو حد عطل Show hidden files، بس مش هتظهر في البحث' },
  { category_id: 1, title: 'حل مشكلة عدم تعرف الكمبيوتر على USB', body: 'USB flash أو هارد خارجي مش بيظهر في My Computer خالص.\n\nالحل:\n1. جرب USB تاني عشان تتأكد إن المشكلة مش في الفلاشة\n2. افتح Disk Management (diskmgmt.msc) وشوف لو ظهر\n3. لو ظهر بدون حرف (Drive Letter)، كليك يمين > Change Drive Letter\n4. في Device Manager: Uninstall USB driver > Restart\n5. جرب USB على منفذ تاني (خاصة في ضهر الكمبيوتر)\n6. لو USB 3.0 وواصل في 2.0، جرب منفذ تاني' },
  { category_id: 1, title: 'إزاي أزيل برنامج ما يتحذفش — خطوات إجبارية', body: 'في برنامج مش عايز يتحذف وبيظهر error "Access Denied".\n\nالحل:\n1. جرب Revo Uninstaller — بيمسح الـ Registry كمان\n2. شغّل CMD كـ Admin: wmic product where "name=\'program_name\'" call uninstall\n3. جرب Safe Mode — في الوضع الآمن مفيش حماية\n4. استخدم IObit Unlocker عشان تقفل العملية وتمسح\n5. مسح يدوي للفولدر + Registry (regedit): HKEY_LOCAL_MACHINE > SOFTWARE > Microsoft > Windows > CurrentVersion > Uninstall' },
  { category_id: 1, title: 'مشكلة صوت تصفير من الكمبيوتر — إزاي أعرف العطل؟', body: 'الكمبيوتر بيصدر صوت بيب/تصفير (Beep) عند التشغيل.\n\nالحل:\n- 1 بيب قصير: كل شيء طبيعي (POST passed)\n- 1 بيب طويل + 2 قصير: مشكلة في كارت الشاشة\n- بيب مستمر: مشكلة في الرامات\n- 3 بيبات: مشكلة في لوحة المفاتيح\n- 4 بيبات: مشكلة في الماذربورد\nتحتاج تفصل الرامات وتنضفها وترجع تركبهاأو تشيل كارت الشاشة وترجعه' },
  { category_id: 1, title: 'ازاي أعمل Virtual Machine على ويندوز من غير برامج؟', body: 'عايز أجرب نظام تشغيل تاني من غير ما أثبته على جهازي.\n\nالحل:\n1. فعّل Virtualization من BIOS (غالباً F2 أو Del عند التشغيل)\n2. افتح Turn Windows features on or off\n3. فعّل Hyper-V (متوفر في Pro و Enterprise)\n4. افتح Hyper-V Manager\n5. Create > Virtual Machine\n6. اختار ايزو النظام اللي عايزه\n7. خلي الرام 2-4 جيجا والهارد 30-50 جيجا' },
  { category_id: 1, title: 'حل مشكلة الشاشة السوداء عند تشغيل الكمبيوتر', body: 'الكمبيوتر يشتغل (المروحة والصوت) بس الشاشة سودة.\n\nالحل:\n1. افصل كابل الشاشة ووصله تاني\n2. لو في كارت شاشة خارجي، غير لكابل الماذربورد\n3. افصل الرامات ونضفها وارجعها (أول حاجة تجربها)\n4. شيل بطارية الـ CMOS لمدة 30 ثانية وارجعها\n5. جرب شاشة تانية لو متوفرة\n6. لو لسه، غالباً المشكلة في كارت الشاشة نفسه' },
  { category_id: 1, title: 'ازاي أسرع الإنترنت على الكمبيوتر — 10 خطوات', body: 'الإنترنت بطيء على الكمبيوتر بس سريع على الموبايل.\n\nالحل:\n1. غير DNS لـ Google (8.8.8.8) أو Cloudflare (1.1.1.1)\n2. حدث درايفر الواي فاي\n3. ابعد الراوتر عن الحوائط والمعدات الكهربية\n4. جرب 5 GHz بدل 2.4 GHz لو الراوتر يدعم\n5. عطل برامج الخلفية اللي بتستهلك نت\n6. استخدم Ethernet سلكي (أسرع وأثبت)\n7. افحص الفيروسات: ممكن في برنامج بيستهلك النت\n8. استخدم برنامج TCP Optimizer لتحسين الإعدادات\n9. اعمل Reset للراوتر (افصل الكهرباء 30 ثانية)\n10. لو المشكلة مستمرة، اتصل بمزود الخدمة' },
  { category_id: 1, title: 'مشكلة الكمبيوتر بيعمل Restart لوحده — الأسباب والحل', body: 'الكمبيوتر بيعيد تشغيل نفسه من غير مقدمات أثناء الشغل.\n\nالحل:\n1. افحص درجة حرارة المعالج (استخدم HWMonitor)\n2. لو الحرارة عالية غير المعجون الحراري\n3. افحص الرامات: mdsched.exe\n4. عطل Automatic Restart: System Properties > Advanced > Startup and Recovery > Uncheck "Automatically restart"\n5. شوف سجل الأخطاء: Event Viewer > Windows Logs > System\n6. جرب مصدر طاقة تاني لو في تقطيع في الكهرباء' },
  { category_id: 1, title: 'ازاي أعمل Partition للهارد ديسك من غير برامج؟', body: 'عايز أقسم الهارد C: لقسمين.\n\nالحل:\n1. كليك يمين على Start > Disk Management\n2. كليك يمين على القسم اللي عايز تصغر > Shrink Volume\n3. اختار المساحة بالميجابايت (100 جيجا = 102400 MB)\n4. هيظهر مساحة Unallocated\n5. كليك يمين عليها > New Simple Volume\n6. اتبع المعالج > اختار حرف واسم للقسم الجديد\n7. انتهى — القسم الجديد ظهر في My Computer\n8. نصيحة: متقلش عن 100 جيجا للقسم C:' },
  { category_id: 1, title: 'إزاي أمنع البرامج إنها تشتغل مع بداية التشغيل؟', body: 'الكمبيوتر بيبطء لأنه بيحمل برامج كتير مع بداية التشغيل.\n\nالحل:\n1. افتح Task Manager (Ctrl + Shift + Esc)\n2. اضغط على Startup tab\n3. شوف البرامج اللي Enabled وإستهلاكها\n4. اختار أي برنامج مش ضروري > Disable\n5. البرامج اللي ممكن تعطلها: Skype, Spotify, Adobe, Teams, Discord\n6. البرامج اللي سيبه: Antivirus, Drivers\n7. كمان: Settings > Apps > Startup — نفس الحاجة\n8. بعد تعطيل البرامج، إعادة تشغيل وهتلاحظ فرق' },
  { category_id: 1, title: 'مشكلة الماوس يعلق أو يبطء — حل سريع', body: 'الماوس بيعلق كل شوية وخصوصاً في الجيمنج.\n\nالحل:\n1. غير البطاريات (لو وايرلس)\n2. جرب USB منفذ تاني — الأفضل 2.0 بدل 3.0\n3. عطل Enhanced Pointer Precision: Mouse settings > Additional mouse options > Pointer Options > Uncheck\n4. نظف مستشعر الماوس (اللمبة من تحت)\n5. لو ماوس لاسلكي، بعّد الـ Receiver عن الراوتر\n6. استخدم Mouse Rate Checker — لو النسبة قليلة، غير السطح\n7. للماوس الجيمنج: حدث البرنامج بتاعه (Logitech G Hub / Razer Synapse)' },

  // ===== Mobile & Apps (21-40) =====
  { category_id: 2, title: 'إزاي أحل مشكلة بطء الأندرويد بعد فترة؟', body: 'الموبايل بقى تقيل بعد 6 شهور استخدام.\n\nالحل:\n1. امسح كاش التطبيقات: Settings > Storage > Cached data > Clear\n2. استخدم Files by Google لتنظيف الملفات الوهمية\n3. عطل أو عزل التطبيقات اللي مش مستخدمها\n4. فعّل Developer Options وقلل Window animation scale لـ 0.5x\n5. جرب بدائل خفيفة: Facebook Lite بدل Facebook\n6. اعمل فورمات (Factory Reset) كحل أخير\n7. قبل الفورمات، اعمل Backup للصور والفيديوهات' },
  { category_id: 2, title: 'حل مشكلة التطبيق لا يستجيب (App Not Responding)', body: 'التطبيق بيفتح بس بعد شوية بيكتب "التطبيق لا يستجيب".\n\nالحل:\n1. Force Stop: Settings > Apps > التطبيق > Force Stop\n2. امسح الكاش: Storage > Clear Cache\n3. حدث التطبيق من المتجر\n4. لو مشكلة مستمرة: Clear Data (هيمسح بيانات الدخول)\n5. أعد تشغيل الموبايل\n6. لو لسه، أمسح التطبيق ونزله تاني\n7. تاكد إن عندك مساحة كافية في التخزين (10% على الأقل)\n8. لو التطبيق مهم، جرب النسخة القديمة (APK من مصدر موثوق)' },
  { category_id: 2, title: 'ازاي أعمل تصوير شاشة (Screenshot) في أي موبايل؟', body: 'عايز أعمل سكرين شوت بس مش عارف الطريقة.\n\nلأندرويد:\n- زر الطاقة + خفض الصوت معاً (الأغلب)\n- أو سحب البطارخ (Quick Settings) وتلاقي أيقونة Screenshot\n- لـ Samsung: كف اليد على الشاشة (Palm swipe)\n- لبعض الموبايلات: زر الطاقة 3 مرات\n\nللايفون:\n- الجانب الأيمن + رفع الصوت (Face ID)\n- الجانب الأيمن + Home (Touch ID)\n- أو AssistiveTouch > Screenshot\n\nالسكرين شوت بينحفظ في مجلد Screenshots في المعرض' },
  { category_id: 2, title: 'مشكلة البطارية بتخلص بسرعة — حلول فعالة', body: 'البطارية بتخلص في نص اليوم من غير استخدام كتير.\n\nالحل:\n1. شوف إيه بيستهلك البطارية: Settings > Battery > Usage\n2. عطل Background Activity للتطبيقات اللي مش مهمة\n3. قلل سطوع الشاشة أو فعّل Adaptive Brightness\n4. عطل GPS والبلوتوث لو مش مستخدمهم\n5. استخدم Dark Mode (لو شاشة AMOLED — بيفرق فعلاً)\n6. عطل Always On Display\n7. حافظ على شحن البطارية بين 20-80%\n8. لو البطارية قديمة (سنتين+)، غالباً محتاج تغيير' },
  { category_id: 2, title: 'ازاي أرجع رسائل واتساب محذوفة؟', body: 'مسحت رسالة واتساب غلط بالغلط وعايز أرجعها.\n\nالحل:\n1. Backup على Google Drive: امسح الواتساب ونزله تاني\n2. أثناء الإعداد، اختار Restore from Google Drive\n3. لو الباك أب قديم، جرب برنامج Dr.Fone (يدعم الأندرويد)\n4. للايفون: Restore from iCloud Backup\n5. ملاحظة: لازم الباك أب يكون قبل مسح الرسالة\n6. للوقاية: فعّل Backup تلقائي يومي: Settings > Chats > Chat backup > Back up to Google Drive > Daily' },
  { category_id: 2, title: 'إزاي أنقل صور من موبايل لموبايل من غير كابل؟', body: 'عايز أنقل صور من الأندرويد القديم للجديد.\n\nالحل:\n1. Google Photos: حمل الصور عالكلود ونزلها على الجديد\n2. Nearby Share (أندرويد ← أندرويد): افتح الصور > Share > Nearby Share\n3. Quick Share (Samsung): أسرع حل لسامسونج\n4. Send Anywhere: تطبيق — حد أقصى مجاني 2 جيجا\n5. AirDrop: للايفون مع بعض\n6. وصل الموبايلين بكابل OTG: أسرع وأسهل\n7. استخدم التطبيق الرسمي للشركة: Smart Switch (Samsung) أو Phone Clone (Xiaomi)' },
  { category_id: 2, title: 'حل مشكلة التخزين ممتلئ والأندرويد بيشتكي', body: 'جوالك مش عايز يصور أو ينزل تطبيقات لأن التخزين مليان.\n\nالحل:\n1. امسح الكاش: Files by Google > Clean\n2. شوف إيه أكبر الملفات: Files > Large files\n3. انقل الصور لـ Google Photos (توفير 15 جيجا)\n4. امسح التطبيقات اللي مش مستخدمها (خلص 3 شهور)\n5. استخدم SD Card (لو الموبايل يدعم): انقل الموسيقى والصور للكارت\n6. امسح الداونلودات: مجلد Download غالباً مليان\n7. في Settings > Storage > Smart Storage: فعّل الحذف التلقائي للباك أب القديم' },
  { category_id: 2, title: 'إزاي أعمل حظر للإعلانات في الأندرويد؟', body: 'الإعلانات في التطبيقات والمتصفح مزعجة جداً.\n\nالحل:\n1. متصفح Brave: بيحظر الإعلانات تلقائياً\n2. AdGuard: أقوى برنامج حظر إعلانات (مدفوع)\n3. Blokada: مجاني ومفتوح المصدر — بيعمل VPN وهمي\n4. Firefox + uBlock Origin: أحسن combo على الأندرويد\n5. Private DNS: Settings > Connections > More > Private DNS > dns.adguard.com\n6. للراوتر: ثبت AdGuard Home أو Pi-hole على الشبكة كلها\n7. AdLock: ممتاز لحظر إعلانات التطبيقات' },
  { category_id: 2, title: 'مشكلة الواي فاي بيفصل لوحده في الموبايل', body: 'الواي فاي بيفصل كل شوية وبيرجع تاني.\n\nالحل:\n1. Settings > Wi-Fi > اسم الشبكة > Forgot > إعادة الاتصال\n2. عطل Wi-Fi Optimization: Settings > Developer options\n3. غير DNS لـ 1.1.1.1 (Cloudflare): Settings > Wi-Fi > Modify network > IP settings > Static > DNS 1: 1.1.1.1\n4. عطل Smart Network Switch (التبديل التلقائي للبيانات)\n5. انسي الشبكة من Settings > Wi-Fi > Forgot\n6. جرب نطاق 5 GHz بدل 2.4 GHz\n7. لو لسه، امسح كاش الـ Wi-Fi: Settings > Apps > Wi-Fi > Clear cache' },
  { category_id: 2, title: 'ازاي أمنع التطبيقات إنها تاخد صلاحيات من غير ما أعرف؟', body: 'التطبيقات بتطلب صلاحيات مش محتاجتها.\n\nالحل:\n1. Settings > Apps > التطبيق > Permissions\n2. عطل أي صلاحية مش ضرورية (مثلاً: تطبيق حاسبة عايز الكاميرا؟ لا)\n3. للتطبيقات الجديدة: احنا "Ask every time" بدل "While using"\n4. خد بالك من: الـ Microphone، Camera، Location، Contacts\n5. راجع قائمة التطبيقات اللي عندها Full Internet Access\n6. استخدم "Permission Manager" في Settings > Privacy\n7. التزم بمبدأ: لو مش ضروري للتطبيق يشتغل، عطله' },
  { category_id: 2, title: 'حل مشكلة الشاشة الزرقاء في بعض تطبيقات الأيفون', body: 'التطبيق بيفتح ويطفي (Crash) بعد شوية.\n\nالحل:\n1. أغلق التطبيق من التطبيقات الحديثة (App Switcher)\n2. أعد تشغيل الجوال\n3. حدث التطبيق من App Store\n4. امسح التطبيق ونزله تاني\n5. لو الأيفون قديم، جرب آخر إصدار iOS يدعمه جهازك\n6. تاكد من التخزين الكافي (أقل حاجة 1 جيجا فاضي)\n7. للأسف، لو إصدار iOS قديم جداً، التطبيقات الجديدة مش هتشتغل' },
  { category_id: 2, title: 'إزاي أسجل مكالمة في الأندرويد 12 و 13؟', body: 'عايز أسجل مكالمات تلقائياً.\n\nالحل:\n1. أندرويد 12+: Google Phone app بيدعم تسجيل المكالمات في بعض المناطق\n2. افتح Phone > Settings > Call recording\n3. لو مش متاح منطقتك، جرب تطبيق Cube Call Recorder\n4. لـ Samsung: أداتهم مدمجة — Phone > Three dots > Settings > Record calls\n5. Xiaomi: عندهم خاصية تسجيل مدمجة\n6. تنبيه قانوني: في بعض البلدان لازم تخبر الطرف التاني بالتسجيل' },
  { category_id: 2, title: 'مشكلة الصوت واطي في الموبايل حتى على أعلى مستوى', body: 'صوت السماعة واطي حتى بعد ما أرفع الصوت لآخر حاجة.\n\nالحل:\n1. تأكد إن مش في حاجة بتسد السماعة (تراب، جراب)\n2. Settings > Sound > Equalizer: ارفع الـ Frequencies كلها\n3. استخدم تطبيق Volume Booster (زي Goodev)\n4. لأندرويد: Developer options > Disable absolute volume\n5. لقم بتنظيف السماعة بفرشاة ناعمة\n6. لو لسه، غالباً السماعة الداخلية تعطلت وتحتاج صيانة' },
  { category_id: 2, title: 'ازاي أعمل اتصال فيديو جماعي من غير واتساب؟', body: 'عايز أعمل فيديو كول جماعي مع الأهل.\n\nالبدائل:\n- Zoom: لحد 100 شخص مجاني (40 دقيقة للمكالمات الطويلة)\n- Google Meet: مجاني، سهل، مدمج مع جيميل\n- Telegram: لحد 1000 شخص فيديو\n- Messenger: سهل لو الكل عنده فيسبوك\n- Discord: ممتاز للجروبات التقنية والجيمنج\n- FaceTime: للايفون مع بعض — أفضله من حيث الجودة\n- Signal: مشفر وآمن\nكل التطبيقات دي مجانية ومتوفرة على أندرويد وآيفون' },
  { category_id: 2, title: 'حل مشكلة النوتifications مش بتظهر في الأندرويد', body: 'الإشعارات مش بتظهر للتطبيقات — لازم أفتح التطبيق عشان أشوف.\n\nالحل:\n1. Settings > Apps > التطبيق > Notifications > فعّل كل الخيارات\n2. عطل Do Not Disturb لو شغال\n3. Settings > Battery > Optimization > اختار "Don\'t optimize" للتطبيق\n4. Settings > Apps > Special access > Battery optimization > Don\'t optimize\n5. في بعض الهواتف (Xiaomi, Oppo, Huawei): Settings > Apps > Autostart — فعّله\n6. تأكد إن الموبايل مش في Power Saving Mode (بيوقف الإشعارات)' },
  { category_id: 2, title: 'إزاي أسترجع صور محذوفة من الأندرويد بدون برامج؟', body: 'مسحت صور بالغلط من المعرض.\n\nالحل:\n1. افتح Photos (Google Photos) أو المعرض\n2. اتجه إلى Trash أو Recently Deleted\n3. الصور بتفضل 30 يوم (Google Photos) أو 15-30 (حسب الهاتف)\n4. اختار الصور اللي عايزها > Restore\n5. لو مش في Trash، جرب Files by Google > Categories > Recently deleted\n6. ملاحظة: لو مسحت من Files by Google، للأسف متقدرش ترجعها\n7. للوقاية: فعّل Google Photos Backup عشان صورك دايماً في الكلاود' },
  { category_id: 2, title: 'مشكلة التحديثات التلقائية بتستهلك بيانات — إزاي أتحكم؟', body: 'التطبيقات بتتحدث على بيانات المحمول وبتخلص الباقة.\n\nالحل:\nأندرويد:\n- Play Store > Profile > Settings > Network preferences > Auto-update apps > Over Wi-Fi only\n- App-specific: تلقى كل تطبيق إعداداته\n\niOS:\n- Settings > App Store > App Updates: عطلها على البيانات\n\nكذلك:\n- Settings > Connections > Data usage > عطل Background data للتطبيقات\n- استخدم Datally (تطبيق جوجل للتحكم في البيانات)\n- فعّل Data Saver في الأندرويد' },
  { category_id: 2, title: 'ازاي أعمل فورمات للموبايل الأندرويد (Factory Reset)؟', body: 'عايز أمسح كل حاجة وارجع الموبايل زي ما هو جديد.\n\nالخطوات:\n1. Settings > General Management > Reset\n2. Factory Data Reset\n3. هيحذف كل حاجة: صور، تطبيقات، حسابات\n4. اعمل Backup قبل الفورمات (Google Photos + Contacts)\n5. اضغط Reset > اكتب PIN/PASSWORD\n6. استنى — الموبايل هيرجع زي الفابريكة (5-10 دقايق)\n7. هتحتاج تعيد تسجيل الدخول لجوجل وآبل\n8. الملفات اللي في SD Card مش بتتمسح (افصلها قبل)' },

  // ===== Programming (41-60) =====
  { category_id: 3, title: 'إزاي أبدأ تعلم البرمجة من الصفر؟ — دليل كامل', body: 'عايز أتعلم برمجة ومش عارف أبدأ منين.\n\nالخطة:\n1. أختار لغة سهلة: Python — الأفضل للمبتدئين\n2. مصادر مجانية:\n   - FreeCodeCamp (عربي وإنجليزي)\n   - Codecademy\n   - CS50 من Harvard (على يوتيوب)\n3. المواضيع الأساسية:\n   - Variables و Data Types\n   - Loops و Conditions\n   - Functions\n   - Arrays/Lists\n   - Objects/Dictionaries\n4. أول مشروع: آلة حاسبة — Todo List — تطبيق طقس\n5. الأهم: مارس كل يوم 30 دقيقة على الأقل\n6. انضم لمجتمعات: GitHub، StackOverflow، Reddit\nنصيحة: متتعلمش 10 لغات في نفس الوقت — ركز على لغة واحدة لحد الإتقان' },
  { category_id: 3, title: 'الفرق بين Frontend و Backend و Full Stack — أختار إيه؟', body: 'مش فاهم الفرق بين التخصصات.\n\nFrontend (الواجهة):\n- HTML, CSS, JavaScript, React, Vue\n- مهتم بشكل الموقع وتفاعل المستخدم\n- الراتب: متوسط\n\nBackend (الخلفية):\n- Node.js, Python, PHP, Java, Databases\n- مهتم بالمنطق والبيانات والأمان\n- الراتب: أعلى شوية\n\nFull Stack:\n- الاتنين مع بعض\n- رواتب أعلى لكن مسؤولية أكبر\n- محتاج تعرف Frontend + Backend + DevOps\n\nالاختيار:\n- لو بتحب التصميم والشكل: Frontend\n- لو بتحب المنطق والبيانات: Backend\n- لو عايز تشتغل لوحدك على مشاريع: Full Stack\nتبدأ بـ Frontend وبعدين تتعلم Backend — ده أسهل طريق' },
  { category_id: 3, title: 'إزاي أعمل موقع ببلاش — الدليل الكامل 2026', body: 'عايز أعمل موقع Personal Website من غير ما أدفع فلوس.\n\nالخطوات:\n1. Code: استخدم HTML + CSS + JavaScript (أو Next.js)\n2. استضافة مجانية: \n   - Vercel: أفضل حاجة لـ Next.js\n   - Netlify: مناسب للمواقع البسيطة\n   - GitHub Pages: لو الموقع Static HTML\n3. Domain مجاني:\n   - Vercel: yourapp.vercel.app\n   - Netlify: yourapp.netlify.app\n   - GitHub Pages: username.github.io\n4. لو عايز Domain مخصوص:\n   - Freenom: .tk و .ml و .ga مجاني (بس قفل دلوقتي)\n   - Namecheap: .com ب ٨ دولار\n5. الأهم: المحتوى — اكتب حاجة مفيدة عشان الناس تزورك\nنصيحة: ابدأ بـ Next.js على Vercel — أحسن combo مجاني' },
  { category_id: 3, title: 'إيه هي الـ API وإزاي أستخدمها — شرح مبسط', body: 'دايماً بسمع API بس مش فاهم إيه هي.\n\nAPI = Application Programming Interface\nببساطة: وسيلة تواصل بين برنامجين.\n\nمثال:\n- عايز تعرف الطقس في تطبيقك\n- بتعمل طلب (Request) لـ API بتاعة الطقس\n- الـ API ترجعلك بيانات (Response) — غالباً JSON\n- تطبيقك يعرضها للمستخدم\n\nإزاي تستخدم API:\n```javascript\nfetch(\'https://api.example.com/weather?city=cairo\')\n  .then(res => res.json())\n  .then(data => console.log(data))\n```\nمواقع APIs مجانية:\n- OpenWeatherMap\n- GitHub API\n- REST Countries\n- PokeAPI\n- JSONPlaceholder (للتجارب)' },
  { category_id: 3, title: 'إيه أفضل لغة برمجة للربح من الإنترنت؟', body: 'عايز أتعلم لغة برمجة عشان أشتغل Freelance.\n\nالأفضل للربح في 2026:\n\n1. JavaScript/TypeScript — الطلب الأعلى\n   - Frontend: React, Next.js\n   - Backend: Node.js\n   - Apps: React Native\n   - متوسط السعر: 30-80$/ساعة\n\n2. Python — الأسرع في التعلم\n   - AI/Data Science: 50-100$/ساعة\n   - Web: Django/Flask\n   - Automation\n\n3. PHP — طلب عربي عالي جداً\n   - WordPress: 20-50$/ساعة\n   - كتير شغل في الوطن العربي\n\n4. Dart/Flutter — للتطبيقات\n   - تطبيقات موبايل: 40-80$/ساعة\n\nنصيحة: اتعلم JavaScript أولاً — الطلب الأعلى والخيارات الأكثر' },
  { category_id: 3, title: 'مشكلة الكود مش شغال — إزاي أصلحها بنفسي؟', body: 'كتبت كود وبيطلع errors ومش عارف أصلحه.\n\nطريقة حل المشاكل:\n1. اقرأ الـ Error message كويس — غالباً بيساعدك تعرف الخطأ\n2. استخدم Google: انسخ الـ error وحط بين "" — هتلاقي حلول\n3. استخدم console.log() / print() عشان تشوف القيم\n4. راجع الـ StackOverflow — الأغلب حد تاني عنده نفس المشكلة\n5. اختبر الكود جزء جزء: قسم الكود واختبر كل جزء لوحده\n6. استخدم Debugger:\n   - VS Code: F5 > اختار Node.js\n   - Chrome DevTools للـ Frontend: F12 > Sources\n7. اشرح المشكلة لشخص تاني (Rubber Duck Debugging)\nالأهم: متقلقش — كل المبرمجين بتروح ساعات في مشاكل' },
  { category_id: 3, title: 'إزاي أعمل API بنفسي باستخدام Next.js', body: 'عايز أعمل API خاص بتطبيقي.\n\nفي Next.js أسهل حاجة — الـ App Router يدعم API Routes:\n```typescript\n// app/api/hello/route.ts\nexport async function GET() {\n  return Response.json({ message: \'مرحباً\' })\n}\n\nexport async function POST(req: Request) {\n  const body = await req.json()\n  return Response.json({ received: body })\n}\n```\n\nالإضافة:\n- ربط بـ Supabase أو MongoDB\n- Authentication باستخدام JWT\n- Rate Limiting لحماية API\n- Swagger/OpenAPI للتوثيق\n\nالـ API هيكون على:\nhttps://your-site.vercel.app/api/hello\n\nميزة Next.js: الـ API بتشتغل كـ Serverless Functions — تدفع على حسب الاستخدام بس' },
  { category_id: 3, title: 'الفرق بين Git و GitHub — شرح بسيط', body: 'كل المبرمجين بيقولوا Git و GitHub بس إيه الفرق؟\n\nGit:\n- نظام تحكم في الإصدارات (Version Control)\n- شغال على جهازك (Local)\n- بيسجل كل التعديلات على الكود\n- أقدر أرجع لأي نسخة قديمة\n- أوامره: git add, git commit, git branch\n\nGitHub:\n- منصة سحابية (Cloud) لرفع أكواد Git\n- مشاركة الكود مع فريق عملك\n- استضافة المشاريع مفتوحة المصدر\n- إضافات: Issues, Pull Requests, Actions\n- بدائل: GitLab, Bitbucket\n\nالخلاصة:\n- Git = الأداة على جهازك\n- GitHub = المكان اللي بترفع فيه الأكواد\nمتستغناش عن الاثنين في أي مشروع برمجي' },
  { category_id: 3, title: 'إزاي أحمي موقعي من هجمات الـ SQL Injection؟', body: 'SQL Injection من أشهر الثغرات الأمنية في المواقع.\n\nإيه هي؟\nالمهاجم بيكتب كود SQL في حقل الإدخال (Form) عشان يسرق قاعدة البيانات.\n\nازاي تحمي:\n1. استخدم Parameterized Queries (أهم حاجة)\n   - لا: `SELECT * FROM users WHERE name = \'` + input + `\'`\n   - صح: `SELECT * FROM users WHERE name = $1` مع parameter\n2. استخدم ORM (زي Prisma, TypeORM)\n3. فعّل Input Validation + Sanitization\n4. استخدم Prepared Statements\n5. ممنوع: صلاحيات قاعدة بيانات عالية للتطبيق\n6. فعّل Web Application Firewall (WAF)\n7. اختبر موقعك: استخدم OWASP ZAP\nمعلومة: 70% من هجمات المواقع بتستخدم SQL Injection' },
  { category_id: 3, title: 'إزاي أعمل Chat App باستخدام WebSockets؟', body: 'عايز أعمل تطبيق شات في الوقت الفعلي (Real-time).\n\nالحل باستخدام WebSockets:\n```javascript\n// Server (Node.js + ws)\nconst WebSocket = require(\'ws\')\nconst wss = new WebSocket.Server({ port: 8080 })\n\nwss.on(\'connection\', ws => {\n  ws.on(\'message\', msg => {\n    wss.clients.forEach(c => c.send(msg.toString()))\n  })\n})\n```\n\nفي Next.js:\n1. استخدم Socket.IO (يدعم fallback)\n2. api/socket/route.ts لإدارة الاتصالات\n3. Client: استخدم useSocket hook\n\nخدمات جاهزة:\n- Pusher (مجاني لحد 100 اتصال)\n- Supabase Realtime (أفضل مع Supabase)\n- Ably\n- Firebase Realtime Database\nأسهل طريقة: Supabase Realtime — بسيطة ومجانية' },
  { category_id: 3, title: 'أفضل VS Code Extensions للمبرمج العربي 2026', body: 'الإضافات اللي بتساعد المبرمج العربي.\n\nالإضافات الأساسية:\n- **ESLint**: تصحيح الأخطاء\n- **Prettier**: تنسيق الكود\n- **GitLens**: تحكم في Git داخل VS Code\n- **Live Server**: عرض HTML مباشر\n- **Path Intellisense**: اقتراح المسارات\n\nللعرب:\n- **Arabic Code Spell Checker**: تدقيق الكلمات العربية\n- **vscode-pdf**: فتح PDF داخل VS Code\n- **Markdown All in One**: سهولة كتابة الوثائق\n\nللتخصص:\n- **Tailwind CSS IntelliSense** (Web)\n- **Python** (لغة)\n- **Thunder Client** (اختبار APIs)\n- **Docker** (حاويات)\n- **Error Lens** (إظهار الأخطاء مباشرة)\n\nالإعدادات المهمة:\n```json\n{\n  \"editor.formatOnSave\": true,\n  \"editor.minimap.enabled\": false,\n  \"workbench.colorTheme\": \"One Dark Pro\"\n}\n```' },
  { category_id: 3, title: 'إزاي أستخدم GitHub Actions لنشر الموقع تلقائياً', body: 'عايز كل ما أعمل push للكود، الموقع ينشر لوحده.\n\nGitHub Actions = CI/CD مجاني من GitHub.\n\nمثال لـ Next.js على Vercel:\n1. اربط GitHub بـ Vercel (من Vercel Dashboard)\n2. Vercel GitHub Integration: كل push بينشر تلقائياً\n3. لو عايز تعمل بنفسك:\n\n```yaml\n# .github/workflows/deploy.yml\nname: Deploy\non: [push]\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm install\n      - run: npm run build\n      - uses: peaceiris/actions-gh-pages@v3\n        with:\n          github_token: $\n          publish_dir: .next\n```\n\nمميزات: مجاني، مفيش ليميت للـ Public repos، 2000 دقيقة/شهر للـ Private' },
  { category_id: 3, title: 'إزاي أتعلم TypeScript من JavaScript — الفروق الأساسية', body: 'TypeScript = JavaScript + Types.\n\nليه تستخدم TypeScript:\n- اكتشاف الأخطاء قبل التشغيل\n- Auto-complete أفضل\n- كود أوضح وأسهل للفريق\n\nأهم الفروق:\n```typescript\n// JavaScript\nlet name = \"Ahmed\"\nlet age = 25\n\n// TypeScript\nlet name: string = \"Ahmed\"\nlet age: number = 25\n\n// Interfaces\ninterface User {\n  id: number\n  name: string\n  email?: string  // optional\n}\n\nconst user: User = { id: 1, name: \"Ahmed\" }\n\n// Union types\nlet result: string | number = \"success\"\nresult = 200  // صح\n\n// Generics\nfunction getFirst<T>(arr: T[]): T {\n  return arr[0]\n}\n\nconst first = getFirst<number>([1, 2, 3])\n```\n\nالانتقال سهل: JavaScript اللي بتعرفه شغال في TypeScript من غير مشاكل' },
  { category_id: 3, title: 'أفضل 10 مصادر مجانية لتعلم البرمجة بالعربي', body: 'أفضل القنوات والمواقع العربية.\n\n1. **كورسيرا (Coursera)**: CS50 بالعربي\n2. **إدراك (Edraak)**: منصة عربية — دورات مجانية بشهادات\n3. **يوتيوب**:\n   - Codezilla: شرح JavaScript و Python رائع\n   - Elzero Web School: HTML, CSS, JS, PHP — متكامل جداً\n   - TheNewBaghdad: دروس متنوعة\n4. **رواق (Rwaq)**: دورات عربية متخصصة\n5. **FreeCodeCamp Arabic**: مجتمع عربي كبير\n6. **أكاديمية حسوب**: مقالات عربية عميقة\n7. **منصة سطر**: دورات عربية تفاعلية\n8. **كتب**:\n   - تعلم JavaScript من الصفر — مجاني PDF\n   - Python for Everybody — كتاب عربي رائع\n9. **تطبيقات**: SoloLearn (جوال)، Mimo (جوال)\n10. **جروبات واتساب وتيليجرام**: مجتمعات عربية للمبتدئين' },
  { category_id: 3, title: 'إزاي أعمل Search Feature في موقعي باستخدام Supabase?', body: 'عايز أضيف خانة بحث على موقعي.\n\nSupabase يدعم Full-Text Search:\n```sql\n-- على قاعدة البيانات\nALTER TABLE threads ADD COLUMN search_vector tsvector\nGENERATED ALWAYS AS (to_tsvector(\'arabic\', title || \' \' || body)) STORED;\n\nCREATE INDEX idx_search ON threads USING GIN(search_vector);\n```\n\nفي API:\n```typescript\nconst { data } = await supabase\n  .from(\'threads\')\n  .select(\'*, author!inner(username)\')\n  .textSearch(\'search_vector\', query, {\n    type: \'websearch\',\n    config: \'arabic\'\n  })\n  .limit(20)\n```\n\nبديل بسيط:\n```typescript\nconst { data } = await supabase\n  .from(\'threads\')\n  .select()\n  .ilike(\'title\', `%${query}%`)\n```\nFull-Text Search أقوى: بيجيب نتائج أكتر، بيدعم اللغة العربية، والأسرع' },
  { category_id: 3, title: 'إزاي أربط Supabase بـ Next.js App Router', body: 'الدليل الكامل عشان تربط Supabase بـ Next.js.\n\n1. ثبت الحزمة:\n```bash\nnpm install @supabase/supabase-js\n```\n\n2. أنشئ client:\n```typescript\n// lib/supabase.ts\nimport { createClient } from \'@supabase/supabase-js\'\n\nexport const supabase = createClient(\n  process.env.NEXT_PUBLIC_SUPABASE_URL!,\n  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!\n)\n```\n\n3. استخدمها في Server Component:\n```typescript\n// app/page.tsx\nexport const dynamic = \'force-dynamic\'\n\nexport default async function Page() {\n  const { data } = await supabase\n    .from(\'threads\')\n    .select(\'*\')  \n  \n  return <pre>{JSON.stringify(data, null, 2)}</pre>\n}\n```\n\n4. متغيرات البيئة:\n- NEXT_PUBLIC_SUPABASE_URL=https://xyz.supabase.co\n- NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbG...\n\nمهم: استخدم `force-dynamic` أو `revalidate` عشان البيانات تكون حديثة' },
  { category_id: 3, title: 'مشكلة الـ CORS في APIs — شرح بسيط وحل', body: 'بتحاول تجيب بيانات من API وبيظهر CORS error في المتصفح.\n\nإيه هي CORS؟\n- سياسة أمان في المتصفح\n- بتمنع موقع يطلب بيانات من موقع تاني\n- مثال: موقعك على localhost:3000 عايز يجيب بيانات من api.example.com\n\nالحل الأول (في Backend):\n```typescript\n// Next.js API\nheaders: {\n  \'Access-Control-Allow-Origin\': \'*\',\n  \'Access-Control-Allow-Methods\': \'GET, POST\',\n}\n```\n\nالحل التاني (استخدم Proxy):\n```next.config.js\nasync rewrites() {\n  return [\n    {\n      source: \'/api/:path*\',\n      destination: \'https://external-api.com/:path*\',\n    },\n  ]\n}\n```\n\nالحل التالت: استخدم CORS Proxy مجاني:\n`https://corsproxy.io/?` + URL المطلوب\n\nملاحظة: CORS مشكلة في المتصفح فقط — في Postman أو Server-side مفيش CORS' },
  { category_id: 3, title: 'إزاي أستضيف تطبيق React على Vercel مجاناً', body: 'عايز ترفع تطبيق React على الإنترنت مجاناً.\n\nالخطوات:\n1. ارفع الكود على GitHub (repo عام أو خاص)\n2. افتح vercel.com وسجل بحساب GitHub\n3. Add New > Project\n4. اختر الـ Repository\n5. Vercel هيتعرف تلقائياً إنه React\n6. إعدادات البناء:\n   - Framework: Create React App\n   - Build Command: npm run build (مضبوط تلقائياً)\n   - Output: build\n7. Environment Variables: لو في API Keys\n8. Deploy\n\nكده موقعك على: your-app.vercel.app\nكل ما تعمل push يتحدث تلقائياً.\n\nلـ Next.js:\nأسهل — Vercel هو الـ Creators بتوع Next.js\nالـ Build بينضبط تلقائياً\nتقدر تضيف custom domain من Settings > Domains' },
  { category_id: 3, title: 'ازاي أقرا وأكتب ملفات JSON في JavaScript', body: 'JSON أشهر صيغة لتبادل البيانات.\n\nقراءة JSON:\n```javascript\n// من ملف\nimport data from \'./data.json\'  // ES Modules\nconst data = require(\'./data.json\')  // CommonJS\n\n// من API\nfetch(\'https://api.example.com/data\')\n  .then(res => res.json())\n  .then(data => console.log(data))\n\n// من string\nconst obj = JSON.parse(\'{\"name\": \"Ahmed\"}\')\n```\n\nكتابة JSON:\n```javascript\nconst obj = { name: \"Ahmed\", age: 25 }\nconst jsonString = JSON.stringify(obj, null, 2)\nconsole.log(jsonString)\n// {\n//   \"name\": \"Ahmed\",\n//   \"age\": 25\n// }\n\n// تخزين\nlocalStorage.setItem(\'user\', JSON.stringify(obj))\nconst stored = JSON.parse(localStorage.getItem(\'user\'))\n```\n\nفي Node.js (قراءة وكتابة ملفات):\n```javascript\nimport fs from \'fs\'\nconst data = JSON.parse(fs.readFileSync(\'data.json\', \'utf8\'))\ndata.users.push({ id: 1, name: \"Ahmed\" })\nfs.writeFileSync(\'data.json\', JSON.stringify(data, null, 2))\n```' },

  // ===== AI & Tools (61-80) =====
  { category_id: 4, title: 'ازاي أستخدم ChatGPT باحترافية — 10 خطوات', body: 'كتير بيستخدم ChatGPT بطريقة سطحية — خليني أوريك الاحتراف.\n\n1. **اسأل بطريقة صحيحة (Prompt Engineering)**\n   - وحش: "اكتب لي موضوع"\n   - حلو: "اكتب لي موضوع عن الذكاء الاصطناعي بالعربي، 500 كلمة، بأسلوب بسيط، مع مقدمة وخاتمة"\n\n2. **حدد السياق (Context)**\n   - قوله مين الجمهور المستهدف\n   - حدد النبرة (رسمي/عامي/أكاديمي)\n\n3. **استخدم System Prompt**\n   - في البداية: "أنت خبير تسويق رقمي"\n\n4. **اطلب تنسيق الناتج**\n   - "على شكل جدول"\n   - "نقاط من 1 إلى 5"\n   - "JSON format"\n\n5. **حسن الناتج (Iterate)**\n   - "أضف أمثلة"\n   - "بسط اللغة"\n   - "زودها لـ 800 كلمة"\n\n6. **استخدمها في البرمجة**\n   - اشرحلها المشكلة واطلب الكود\n   - اطلب Debugging\n   - اطلب Refactoring\n\n7. **ترجمة وتحسين نصوص**\n\n8. **ملخصات**: ضع له نص طويل واطلب ملخص\n\n9. **قصة**: اطلب من ChatGPT يكتب سيناريو أو قصة\n\n10. **استمر في التعديل** — أول ناتج مش دايمأ أحسن حاجة' },
  { category_id: 4, title: 'أدوات AI مجانية تغنيك عن البرامج المدفوعة', body: 'أفضل أدوات الذكاء الاصطناعي اللي متكلفش حاجة.\n\n## كتابة\n- **ChatGPT** (مجاني — GPT-3.5، محدود GPT-4)\n- **Claude** (مجاني — أفضل من ChatGPT في التحليل)\n- **Gemini** (مجاني — من Google، مدمج مع Gmail)\n- **DeepSeek** (مجاني — مفتوح المصدر، قوي جداً)\n\n## صور\n- **Bing Image Creator** (مجاني — DALL-E)\n- **Leonardo AI** (مجاني — 150 كريدت/يوم)\n- **Stable Diffusion** (مجاني — يشتغل على جهازك)\n- **Canva AI** (مجاني — تصميم سريع)\n\n## فيديو وموسيقى\n- **CapCut** (مونتاج + AI)\n- **ElevenLabs** (تحويل نص لصوت — صوت عربي ممتاز)\n\n## برمجة\n- **GitHub Copilot** (مجاني للطلاب)\n- **Cursor** (IDE ذكي)\n- **Replit AI** (كتابة كود مع AI)\n\n## متنوع\n- **Perplexity** (بحث ذكي مع مصادر)\n- **Notion AI** (مساعد إنتاجية)' },
  { category_id: 4, title: 'إزاي أعمل AI Chatbot خاص بموقعه باستخدام API', body: 'عايز تضيف شات بوت ذكي لموقعك.\n\n1. استخدم OpenAI API:\n```javascript\nconst response = await fetch(\'https://api.openai.com/v1/chat/completions\', {\n  method: \'POST\',\n  headers: {\n    \'Authorization\': \'Bearer $\',\n    \'Content-Type\': \'application/json\',\n  },\n  body: JSON.stringify({\n    model: \'gpt-3.5-turbo\',\n    messages: [{ role: \'user\', content: \'مرحباً\' }],\n  })\n})\n```\n\n2. حلول جاهزة:\n- **Chatbase**: أبسط حل — ارفع ملفات الموقع واطلع على رابط Embed\n- **SiteSpeak**: خاص بالشركات\n- **Botpress**: منصة مفتوحة المصدر\n\n3. لـ 100% مجاني:\n- استخدم Model مفتوح المصدر (Mistral, Llama, DeepSeek)\n- شغله على Hugging Face Spaces\n- أو استخدم Ollama على السيرفر الخاص\n\nالأفضل للبداية: Chatbase — سريع ومجاني لحد 20 محادثة/شهر' },
  { category_id: 4, title: 'الفرق بين GPT-4 و GPT-3.5 — هل يستحق الترقية؟', body: 'GPT-4 أغلى من GPT-3.5 هل الفرق يستاهل الفلوس؟\n\nGPT-3.5:\n- سرعة عالية\n- ممتاز للأسئلة البسيطة والترجمة\n- 4,000 كلمة (8k context)\n- مناسب 90% من المهام\n- مجاني\n\nGPT-4:\n- أذكى — يفهم سياقات أعمق\n- 25,000 كلمة (128k context) — تقدر تدخل كتاب كامل\n- أفضل في: البرمجة، التحليل، الحسابات\n- قدرة على فهم الصور (Multimodal)\n- أدق في الإجابات التقنية\n- سريع نسبياً (GPT-4o)\n- مدفوع ($20/شهر لـ ChatGPT Plus)\n\nمتى تدفع للترقية؟\n- لو بتستخدمه يومياً في الشغل\n- لو بتكتب كود معقد\n- لو محتاج تحليل مستندات طويلة\n- لو بتشتغل في الأبحاث\n\nللاستخدام العادي: GPT-3.5 كافي وممتاز' },
  { category_id: 4, title: 'إزاي أستخدم AI لتوليد الصور بالعربي', body: 'عايز أ generate صور ومش عارف أفضل أداة.\n\nأفضل أدوات:\n\n1. **Bing Image Creator** (مجاني — أقوى مجاني)\n   - استخدم: https://bing.com/create\n   - اكتب الوصف: "رجل أعمال مصري في مكتب حديث، realistic"\n   - تقدر تضيف عربي والـ AI بيفهم\n\n2. **Leonardo AI** (مجاني — 150 كريدت/يوم)\n   - أفضل في الأنمي والألعاب\n   - عندها Model Trainer\n\n3. **Midjourney** (مدفوع — $10/شهر)\n   - الأفضل في الجودة\n   - لازم Discord\n\n4. **Canva AI** (مجاني)\n   - أسهل حاجة — اكتب وصف واطلع صورة\n   - مدمج في Canva\n\nنصائح للوصف (Prompt):\n- اكتب: "منظر لشاطئ الإسكندرية عند الغروب، realistic, 4k"\n- حط الكلمات دي: realistic, cinematic, detailed\n- لو عايزة Cartoon: vector, cartoon style, flat design\n- حدد نوع الصورة: photograph, digital art, oil painting' },
  { category_id: 4, title: 'إزاي أستخدم DeepSeek — البديل المجاني الأقوى', body: 'DeepSeek من أفضل النماذج مفتوحة المصدر — مجاني بالكامل.\n\nالمميزات:\n- مجاني بدون limits\n- 128k context (زي GPT-4)\n- يدعم رفع ملفات PDF و Word\n- Search متصل بالإنترنت\n- يدعم العربي ممتاز\n\nطريقة الاستخدام:\n1. افتح chat.deepseek.com\n2. اكتب سؤالك\n3. فعّل Deep Think عشان التحليل العميق\n4. ارفع ملفات لو محتاج تحليل\n\nكـ API:\n```javascript\nconst response = await fetch(\'https://api.deepseek.com/v1/chat/completions\', {\n  method: \'POST\',\n  headers: {\n    \'Authorization\': \'Bearer $\',\n    \'Content-Type\': \'application/json\',\n  },\n  body: JSON.stringify({\n    model: \'deepseek-chat\',\n    messages: [{ role: \'user\', content: \'مرحباً\' }],\n  })\n})\n```\n\nالـ API رخيص جداً — 100k token بـ $0.01\nأفضل بديل مجاني لـ ChatGPT.' },
  { category_id: 4, title: 'أفضل 5 أدوات AI للمبرمجين — جربهم النهارده', body: 'أدوات AI بتسهل حياة المبرمج.\n\n1. **GitHub Copilot**\n   - أكمل الكود وأنت بتكتب\n   - يفهم السياق بتاعك\n   - متوفر في VS Code و JetBrains\n   - سعره: $10/شهر (مجاني للطلاب)\n\n2. **Cursor**\n   - IDE كامل مبني على AI\n   - تقدر تكتب feature كاملة بـ prompt واحد\n   - Composer: يعدل أكتر من ملف في نفس الوقت\n   - مجاني (قيود على الـ Premium models)\n\n3. **Claude (Sonnet)**\n   - أقوى في كتابة الكود من ChatGPT\n   - ممتاز لـ Refactoring\n   - واجهة مجانية + API\n\n4. **Tabnine**\n   - بديل Copilot\n   - بيشتغل Local (خصوصية أعلى)\n   - مجاني للاستخدام الأساسي\n\n5. **Continue**\n   - Open source AI assistant\n   - يشتغل مع أي Model (محلي أو Cloud)\n   - جنب VS Code — مجاني بالكامل\n\nنصيحة: جرب Copilot الأول — هو الأسهل والأكثر انتشاراً' },
  { category_id: 4, title: 'إزاي أعمل OCR بالعربي مجاناً — استخراج نص من صور', body: 'عايز تحول صورة فيها نص عربي إلى نص قابل للنسخ.\n\n1. **Google Keep** (مجاني — أسهل حل)\n   - افتح Google Keep > New note > Image\n   - اضغط على الصورة > ثلاث نقاط > Grab image text\n   - يدعم العربي ممتاز\n\n2. **Tesseract.js** (مكتبة مجانية)\n```javascript\nimport Tesseract from \'tesseract.js\'\n\nconst { data } = await Tesseract.recognize(\n  \'image.jpg\', \'ara\',\n)\nconsole.log(data.text)\n```\n\n3. **OnlineOCR.net** (مجاني — 10 صور/ساعة)\n4. **Google Docs** — ارفع الصورة وافتحها بـ Google Docs\n5. **Adobe Acrobat Online** — مدفوع بس ممتاز\n\n6. **PaddleOCR** (Open Source — الأفضل)\n   - يدعم العربي باحترافية\n   - يشتغل على جهازك\n   - `pip install paddleocr`\n\nللصور البسيطة: Google Keep — أسرع وأسهل حاجة' },
  { category_id: 4, title: 'إزاي أستفيد من AI في التسويق الإلكتروني', body: 'الذكاء الاصطناعي غير التسويق — استخدمه صح.\n\n1. **كتابة محتوى**\n   - ChatGPT: بوستات، إعلانات، مقالات\n   - Claude: تحليل الجمهور\n   - Gemini: تحسين SEO\n\n2. **تحليل البيانات**\n   - Google Analytics AI: تحليل سلوك المستخدمين\n   - ChatGPT Analysis: ارفع ملف CSV واطلب تحليل\n\n3. **توليد صور ومنتجات**\n   - Canva AI: تصميم إعلانات\n   - Leonardo AI: صور منتجات\n   - Midjourney: صور عالية الجودة\n\n4. **البريد الإلكتروني**\n   - Mailchimp AI: تحسين العناوين\n   - ChatGPT: كتابة سلسلة إيميلات\n\n5. **الدعم الفني**\n   - Chatbot (Chatbase, Tidio)\n   - رد تلقائي على الأسئلة المتكررة\n\n6. **تحليل المنافسين**\n   - ChatGPT مع Web Search\n   - SimilarWeb\n   - SEMrush\n\nالأهم: استخدم AI لتوفير وقت — مش عشان تعمل كل حاجة من الصفر' },
  { category_id: 4, title: 'DeepSeek vs ChatGPT vs Claude vs Gemini — مقارنة شاملة', body: 'أيهما أفضل في 2026؟\n\n## للبرمجة\n- 1. **Claude 3.5 Sonnet**: الأفضل — يفهم الكود المعقد\n- 2. **GPT-4o**: ممتاز\n- 3. **DeepSeek**: مجاني وقوي\n- 4. **Gemini**: لا بأس\n\n## للكتابة\n- 1. **ChatGPT**: الأفضل في المحتوى الطويل\n- 2. **Claude**: ممتاز في التحليل\n- 3. **DeepSeek**: جيد\n- 4. **Gemini**: جيد مع البحث\n\n## للمحادثة\n- 1. **DeepSeek**: مجاني مع Search\n- 2. **ChatGPT**: سريع\n- 3. **Claude**: دقيق\n- 4. **Gemini**: مدمج مع Google\n\n## السعر\n| النموذج | مجاني؟ | API سعر |\n|---------|--------|--------|\n| ChatGPT 3.5 | ✅ | $0.002/1K |\n| ChatGPT 4 | محدود | $0.03/1K |\n| Claude | ✅ (محدود) | $0.015/1K |\n| DeepSeek | ✅ بالكامل | $0.001/1K |\n| Gemini | ✅ | مجاني لحد 60 طلب/دقيقة |\n\nالخلاصة: استخدم DeepSeek للمجاني، Claude للكود، ChatGPT للكتابة' },
  { category_id: 4, title: 'إزاي أعمل Text to Speech AI بالعربي مجاناً', body: 'تحويل النص إلى كلام عربي طبيعي.\n\n1. **ElevenLabs** (أفضل جودة)\n   - صوت عربي طبيعي جداً\n   - مجاني: 10,000 كلمة/شهر\n   - API متاح\n\n2. **Edge TTS** (مجاني — ممتاز)\n```python\nimport edge_tts\ntext = \"مرحباً بكم في Logixa Help\"\nvoice = \"ar-EG-SalmaNeural\"\nawait edge_tts.Communicate(text, voice).save(\"output.mp3\")\n```\n\n3. **Google Cloud TTS** (مجاني — 1M حرف/شهر)\n\n4. **Hugging Face** (مجاني — Open Source)\n   - Bark (يدعم العربي)\n   - Coqui TTS\n\n5. **أونلاين**:\n   - NaturalReaders\n   - TTSMaker\n   - TextToSpeechFree\n\nأفضل combo مجاني: Edge TTS + ElevenLabs — Edge للاستخدام الكثيف، ElevenLabs للجودة العالية' },
  { category_id: 4, title: 'إزاي أستضيف نموذج AI على السحابة مجاناً', body: 'عايز تشغل نموذج AI على الإنترنت من غير ما تدفع.\n\n**Hugging Face Spaces** (أفضل خيار)\n- مجاني بالكامل\n- يدعم: Gradio, Streamlit, Docker\n- استضافة نماذج LLM (Llama, Mistral, Gemma)\n- 16GB RAM مجاناً\n\nالخطوات:\n1. سجل في huggingface.co\n2. New Space\n3. اختار Gradio + Space Hardware (CPU أو GPU مجاني محدود)\n4. ارفع الكود:\n\n```python\nimport gradio as gr\n\ndef chat(message, history):\n    return f\"مرحباً! قلت: {message}\"\n\ngr.ChatInterface(chat).launch()\n```\n\n**بدائل:**\n- **Google Colab**: GPU مجاني (T4) — جلسات محدودة\n- **Replit**: تشغيل بايثون مجاناً\n- **Fly.io**: 3 تطبيقات مجانية\n- **Railway**: $5 كريدت مجاني\n\nللبداية: Hugging Face Spaces — أبسط وأقوى' },
  { category_id: 4, title: 'ازاي أستخدم AI في تحليل البيانات — Excel و CSV', body: 'AI يقرأ ملفات البيانات ويحللها بدقائق.\n\n1. **ChatGPT + Code Interpreter** (GPT-4)\n   - ارفع ملف Excel/CSV\n   - اطلب: "حلل البيانات واعمل رسم بياني"\n   - ChatGPT يكتب كود بايثون ويشغله\n\n2. **Claude** (Artifacts)\n   - ارفع الملف\n   - اطلب تحليل و Visualizations\n\n3. **Google Sheets AI**\n   - "Explore" feature\n   - اسأل: "What\'s the total sales by category?"\n\n4. **مكتبات بايثون**\n```python\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv(\'data.csv\')\ndf.describe()\ndf.groupby(\'category\').sum().plot(kind=\'bar\')\n```\n\n5. أدوات متخصصة:\n   - Julius AI: محلل بيانات ذكي\n   - Akkio: تحليل تنبؤي (Prediction)\n\nأفضل طريقة: ارفع ملفك لـ ChatGPT Plus (Code Interpreter) — أقوى حل' },
  { category_id: 4, title: 'إزاي أعمل فيديو بالذكاء الاصطناعي — من نص لفيديو', body: 'عايز تحول نص إلى فيديو كامل بالذكاء الاصطناعي.\n\nأفضل أدوات:\n\n1. **Synthesia** (مدفوع — أفضل جودة)\n   - Avatar يتكلم نصك\n   - يدعم العربي\n   - سعره: $30/شهر\n\n2. **HeyGen** (مجاني محدود)\n   - Avatar مجاني (دقيقة واحدة)\n   - جودة ممتازة\n\n3. **Pictory** (مجاني)\n   - يحول المقالات لفيديو\n   - صور وفيديوهات مخزنة\n\n4. **CapCut** (مجاني — ممتاز)\n   - Text to Speech عربي\n   - Auto Captions\n   - قوالب جاهزة\n\n5. **InVideo** (مجاني)\n   - قوابل كثيرة\n   - AI Script Generator\n\n6. **RunwayML** (مجاني محدود)\n   - Gen-2: توليد فيديو من نص\n   - متقدم\n\nللبداية: CapCut — مجاني وكافي' },
  { category_id: 4, title: 'إزاي أستخرج بيانات من أي موقع باستخدام AI', body: 'عايز تجيب بيانات من مواقع من غير ما تكتب كود.\n\n1. **Firecrawl** (أفضل حل)\n   - اكتب URL\n   - يقرا الموقع كله ويعطيك البيانات\n   - يدعم JSON output\n   - مجاني: 500 صفحة\n\n2. **Browse AI**\n   - واجهة رسومية\n   - تعليم الموقع بالضغط (Point and click)\n   - مجاني: محدود\n\n3. **Octoparse**\n   - مجاني للاستخدام الأساسي\n   - يدعم الـ JavaScript\n\n4. **ChatGPT + Code**\n   - اطلب من ChatGPT يكتب لك Web Scraper:\n```python\nimport requests\nfrom bs4 import BeautifulSoup\n\nurl = \'https://example.com\'\nresponse = requests.get(url)\nsoup = BeautifulSoup(response.text, \'html.parser\')\ntitles = soup.find_all(\'h2\')\nfor t in titles:\n    print(t.text)\n```\n\n5. **Apify**\n   - سوق مليان Web Actors\n   - مجاني: $5 كريدت\n\nنصيحة: Firecrawl للسهولة، Python للاحتراف' },

  // ===== Business (81-95) =====
  { category_id: 5, title: 'ازاي أبدأ مشروع صغير أونلاين بـ 0 جنيه', body: 'عايز تشتغل على الإنترنت من غير رأس مال.\n\n1. **Freelancing**\n   - مستقل، خمسات، Upwork\n   - مهارات مطلوبة: كتابة، ترجمة، تصميم، برمجة\n   - ابدأ بسعر منخفض عشان تبني تقييم\n\n2. **الربح من المحتوى**\n   - يوتيوب (بدون فلوس — جوالك كافي)\n   - تيك توك (سهل الإنتشار)\n   - كتابة مقالات على LinkedIn\n\n3. **الربح من المنتجات الرقمية**\n   - كتاب PDF\n   - قالب موقع\n   - كورس مسجل\n   - منصات: Gumroad، Shopify (تجربة مجانية)\n\n4. **Dropshipping**\n   - بيع منتجات من علي إكسبريس بدون تخزين\n   - Shopify + Oberlo\n   - محتاج: تسويق (فيسبوك/تيك توك)\n\n5. **التسويق بالعمولة (Affiliate)**\n   - انضم لبرامج: Amazon Associates\n   - Amazon, AliExpress, Shopify\n   - انشر رابط المنتج وخذ عمولة\n\nالأهم: اختار مجال واحد وابدا — متشتتش بين أكتر من مجال' },
  { category_id: 5, title: 'إزاي أسوي Brand إسم الشركة — من الصفر', body: 'خطوات عملية لبناء علامة تجارية.\n\n1. **الاسم**\n   - قصير (2-4 مقاطع)\n   - سهل النطق بالإنجليزي والعربي\n   - متوفر كدومين .com\n   - متوفر على مواقع التواصل\n   - مثال: Logixa — قصير، مميز، سهل\n\n2. **الشعار (Logo)**\n   - Canva: مجاني وسهل\n   - Looka: AI يصمم لك\n   - Fiverr: $20-50 مصمم محترف\n   - الألوان: اختار 2-3 ألوان (ثابتة)\n   - مثال: Logixa — ذهبي + كحلي + أبيض\n\n3. **الهوية البصرية**\n   - ألوان ثابتة\n   - خط (Font) ثابت: Google Fonts\n   - شكل البوستات والبزنس كارد\n\n4. **التواجد**\n   - موقع: Next.js على Vercel (مجاني)\n   - لينكد إن: بروفايل شركة\n   - تويتر/إكس: تواجد يومي\n\n5. **الصوت (Voice)**\n   - نبرة موحدة في كل مكان\n   - مثال: Logixa = "تقني، محترف، عربي، بسيط"\n\nابدأ بـ Canva + Google Fonts + موقع Vercel — كده عندك Brand في يوم واحد' },
  { category_id: 5, title: 'ازاي أعمل متجر إلكتروني مجاناً', body: 'عايز تبيع منتجات أونلاين من غير شركة استضافة.\n\n1. **Shopify** (تجربة 3 أيام مجاناً — $1/شهر أول 3 شهور)\n   - أسهل حل\n   - قوالب جاهزة\n   - بوابات دفع مدمجة\n\n2. **WooCommerce** (مجاني — بس محتاج استضافة)\n   - WordPress + WooCommerce\n   - استضافة: Hostinger ($2/شهر)\n\n3. **Ecwid** (مجاني — بيع على فيسبوك وانستجرام)\n   - أضف متجرك لأي موقع\n   - مجاني: 10 منتجات\n\n4. **Salla** (سعودي — $20/شهر)\n   - يدعم الدفع السعودي\n   - قوالب عربية\n\n5. **متجر على فيسبوك وانستجرام** (مجاني 100%)\n   - Facebook & Instagram Shops\n   - مجاني بالكامل\n   - تقبل الدفع\n\nللبداية بدون فلوس: افتح متجر على فيسبوك/انستجرام + Ecwid مجاني — $0' },
  { category_id: 5, title: 'أفضل 10 طرق للربح من الإنترنت في مصر 2026', body: 'طرق مجربة للربح مناسبين للسوق المصري.\n\n1. **Freelancing** ($200-1000/شهر)\n   - مستقل، خمسات، Upwork\n   - برمجة، تصميم، ترجمة، كتابة\n\n2. **يوتيوب** ($100-5000/شهر)\n   - المحتوى التقني والعربي مطلوب جداً\n   - الربح من الإعلانات بعد 1000 مشترك\n\n3. **التسويق بالعمولة** ($100-1000/شهر)\n   - Amazon, AliExpress, Jumia\n   - صفحات فيسبوك ومجموعات\n\n4. **دروب شيبينغ** ($200-2000/شهر)\n\n5. **الربح من المواقع (AdSense)** ($100-500/شهر)\n   - محتوى تقني/تعليمي\n   - 1000 زائر/يوم = $100-300\n\n6. **بيع منتجات رقمية** ($100-5000/شهر)\n   - كتب PDF، كورسات، قوالب\n\n7. **المتاجر الإلكترونية** ($300-2000/شهر)\n   - Shopify أو سلة\n   - منتجات مادية من تاجر جملة\n\n8. **التداول والعملات** (مخاطرة عالية)\n\n9. **التطبيقات** ($100-10000/شهر)\n   - تطبيق مفيد + إعلانات\n\n10. **الاستشارات عبر الإنترنت** ($500-2000/شهر)\n    - خبرتك في مجال معين = قيمة\n\nالأفضل للمبتدئين: Freelancing + يوتيوب — دخول سريع' },
  { category_id: 5, title: 'ازاي أسوي صفحة أعمال على Google My Business', body: 'عشان تظهر في خرائط جوجل لما حد يدور على نشاطك التجاري.\n\nالخطوات:\n1. افتح google.com/business\n2. سجل بحساب جوجل بتاعك\n3. اكتب اسم النشاط التجاري\n4. اختار الفئة (Category): شركة برمجة، مطعم، متجر...\n5. أدخل العنوان (بالضبط — عشان يظهر في الخريطة)\n6. اختار هل بتستقبل زوار ولا خدمة توصيل\n7. أدخل رقم الهاتف والموقع\n8. اختار طريقة التحقق:\n   - بطاقة بريدية (تصل في 5-14 يوم)\n   - هاتف (في بعض المناطق)\n   - ايميل (أحياناً)\n9. بعد التحقق: أضف صور وصف نشاطك\n10. طلب مراجعات من العملاء\n\nمهم: الصفحة بتحسن ظهورك في البحث المحلي بشكل كبير' },
  { category_id: 5, title: 'إزاي أكتب Proposal ربحي وفوز بالعميل', body: 'الـ Proposal هو عرض السعر — الطريقة الصح تكسبك العميل.\n\n1. **افهم المشكلة أولاً**\n   - اسأل أسئلة كتير قبل ما تكتب\n   - أظهر إنك فاهم احتياجه\n\n2. **هيكل الـ Proposal**\n   - عنوان قوي\n   - فهمي للمشكلة (أظهر إنك فاهم)\n   - الحل المقترح\n   - الخبرات السابقة (مشاريع مشابهة)\n   - الجدول الزمني\n   - السعر\n   - ضمانات\n\n3. **نصائح**:\n   - السعر: 3 خيارات (Basic, Standard, Premium)\n   - اشرح القيمة مش الميزات\n   - ضيف شهادات عملاء (Testimonials)\n   - خلي الـ Proposal مخصص — مش Copy/Paste\n\n4. **أدوات**:\n   - Better Proposals: تصميم محترف\n   - PandaDoc: توقيع إلكتروني\n   - Google Docs: مجاني\n\nماتكتبش: "أنا عندي خبرة في". اكتب: "حليت مشكلة مشابهة لشركة X ووفرت لهم 40% من التكلفة"' },
  { category_id: 5, title: 'ازاي أحدد سعر خدماتي في البرمجة — دليل التسعير', body: 'محتار تحدد سعر الشغل.\n\n## حسب الخبرة\n- مبتدئ (0-1 سنة): $10-20/ساعة\n- متوسط (1-3 سنوات): $25-50/ساعة\n- محترف (3-5 سنوات): $50-80/ساعة\n- خبير (5+ سنوات): $80-150/ساعة\n\n## حسب نوع المشروع\n- موقع بسيط HTML: $200-500\n- موقع React/Next.js: $500-2000\n- تطبيق موبايل: $2000-10000\n- API + Backend: $1000-5000\n- متجر إلكتروني: $1500-5000\n\n## حسب السوق\n- سوق عربي: $15-40/ساعة\n- Upwork/Fiverr: $20-60/ساعة\n- Toptal: $60-150/ساعة\n- عميل مباشر: $30-80/ساعة\n\n## نصيحة: ما تخفضش السعر\n- السعر المنخفض = عملاء صعبين\n- السعر المرتفع = عملاء محترمين\n- ارفع سعرك 20% وشوف النتيجة' },
  { category_id: 5, title: 'ازاي أستخدم LinkedIn عشان أجيب عملاء وشغل', body: 'LinkedIn أقوى منصة للشغل الحر.\n\n1. **بروفايل محترف**:\n   - صورة شخصية واضحة\n   - عنوان قوي: "Full Stack Developer" مش "مبرمج"\n   - Summary: اكتب عن قيمة بتقدمها\n   - أضف Portfolio (Projects)\n\n2. **انشر محتوى تقني**:\n   - بوست أسبوعياً: "إزاي أصلح..."\n   - مقالات قصيرة\n   - نصائح برمجية\n   - الهاشتاج: #برمجة #ويب #تطبيقات\n\n3. **تواصل مع العملاء**:\n   - مش "عايز شغل" — لأ\n   - اكتب: "لاحظت إن شركتكم عندها مشكلة في X. عايز تقترح حل"\n   - ابعت 10 رسائل يومياً\n\n4. **خدمة Freelancer**:\n   - فعّل Services في بروفايلك\n   - حدد الخدمات والأسعار\n\n5. **Recommendations**:\n   - اطلب من العملاء السابقين توصية\n   - هم أكتر حاجة بتجيب ثقة' },
  { category_id: 5, title: 'إزاي أعمل متجر على إنستجرام و فيسبوك', body: 'البيع على السوشيال ميديا أسهل من متجر كامل.\n\nالخطوات:\n1. حول حسابك لـ Business Account\n2. أنشئ Facebook Page + Instagram Business\n3. Connect: Settings > Business > Connect Facebook\n4. أضف منتجاتك:\n   - افتح Commerce Manager على فيسبوك\n   - Add products > يدوي أو استورد من Shopify\n5. فعّل شوبينغ:\n   - Instagram: Settings > Business > Shopping\n   - اختار Catalog\n6. صور المنتجات:\n   - خلفية بيضاء\n   - صور استخدام\n   - فيديو قصير\n\nنصائح:\n- انشر 3-4 مرات في الأسبوع\n- استخدم Stories + Reels\n- رد على التعليقات بسرعة\n- قدم عروض أول شراء\n- اطلب تقييمات من المشترين' },
  { category_id: 5, title: 'إزاي أعمل Source Income متعددة — مش عشان اعتمد على مصدر واحد', body: 'الاعتماد على مصدر دخل واحد خطأ.\n\nخطة بناء مصادر دخل متعددة:\n\n**المرحلة 1: الأساس (شهر 1-3)**\n- Freelancing (مستقل/Upwork)\n- $500-1000/شهر\n\n**المرحلة 2: المنتجات (شهر 3-6)**\n- كورس مسجل\n- كتاب PDF\n- قالب موقع\n- $200-500/شهر إضافي\n\n**المرحلة 3: المحتوى (شهر 6-12)**\n- يوتيوب\n- موقع بإعلانات\n- $200-1000/شهر إضافي\n\n**المرحلة 4: الأتمتة (شهر 12+)**\n- SaaS صغير\n- Affiliate Marketing\n- استثمارات\n- $1000+ إضافي\n\nالنموذج المثالي:\n```\n50% Freelancing (دخل سريع)\n30% منتجات رقمية (دخل سلبي)\n20% محتوى (نمو طويل المدى)\n```\nالأهم: متوقفش مصدر واحد — كل مصدر يبني على التاني' },

  // ===== General (96-100) =====
  { category_id: 6, title: 'أفضل المواقع المجانية لتعلم أي حاجة أونلاين', body: 'مصادر تعليمية مجانية لكل المجالات.\n\n- **Coursera**: دورات من جامعات عالمية — اختر Audit مجاناً\n- **edX**: مثل كورسيرا — MIT, Harvard دورات\n- **Khan Academy**: رياضيات وعلوم\n- **FreeCodeCamp**: برمجة — مجاني بالكامل\n- **Codecademy**: تفاعلي — أساسيات البرمجة\n- **Duolingo**: لغات\n- **YouTube**: أي حاجة — أهم مصدر تعليمي\n- **MIT OpenCourseWare**: محاضرات MIT كاملة\n- **Google Digital Garage**: تسويق رقمي\n- **HubSpot Academy**: تسويق ومبيعات\n\nنصيحة: كل المصادر دي مجانية بالكامل — في شهادات مدفوعة لو عايز CV' },
  { category_id: 6, title: 'إزاي أحمي نفسي من الاختراق — نصائح للمبتدئين', body: 'الأمن السيبراني مش صعب — ابدأ بهذه الأساسيات.\n\n1. **باسوورد قوي**:\n   - طول 12 حرف على الأقل\n   - أرقام + رموز + حروف كبيرة وصغيرة\n   - استخدم مدير باسوورد: Bitwarden (مجاني)\n\n2. **تحقق بخطوتين (2FA)**\n   - فعّله على كل المواقع المهمة\n   - استخدم Google Authenticator أو Authy\n\n3. **تحديثات**: \n   - حدث ويندوز باستمرار\n   - حدث التطبيقات والمتصفح\n\n4. **Wi-Fi**:\n   - غير باسوورد الراوتر\n   - استخدم WPA2 أو WPA3\n\n5. **احذر من**:\n   - رسائل فيشنج (Phishing): "حسابك مغلق — اضغط هنا"\n   - مواقع مشبوهة\n   - تحميل برامج من مصادر مش موثوقة\n\n6. **استخدم**:\n   - متصفح: Brave أو Firefox\n   - VPN: ProtonVPN (مجاني)\n   - Antivirus: Windows Defender + Malwarebytes' },
  { category_id: 6, title: 'ازاي أعمل CV محترف — نموذج و نصائح', body: 'السيرة الذاتية هي بوابتك للشغل.\n\n**النموذج القوي:**\n1. الاسم + المسمى الوظيفي\n2. ملخص (3 سطور): مين أنت وإيه قيمتك\n3. الخبرات: الشركة، المدة، إنجازين لكل شغلة\n4. المهارات: تقنية + شخصية\n5. التعليم: شهادة + سنة\n6. المشاريع: 2-3 مشاريع\n7. اللغات والشهادات\n\n**نصائح مهمة:**\n- صفحة واحدة لو خبرتك أقل من 5 سنين\n- استخدم فعل قوي: "طورت"، "أنشأت"، "قادت"\n- خليها PDF (مش Word)\n- أضف أرقام: "حسنت الأداء 40%"\n- مينفعش CV طويل — أصحاب العمل بيدققوا 6 ثواني\n\n**أدوات:**\n- Canva (مجاني — قوابل عربية)\n- Novoresume\n- Europass\n- Google Docs (قوالب CV)' },
  { category_id: 6, title: 'ازاي أتغلب على التسويف و أشتغل بجد', body: 'التسويف (Procrastination) أعديProductivity.\n\n1. **القاعدة: 5 دقايق**\n   - أقنع نفسك هتشتغل 5 دقايق بس\n   - غالباً هتكمل بعد ما تبدأ\n\n2. **تقسيم المهام**\n   - مش "اعمل موقع"\n   - "اكتب الـ HTML" ← "ظبط الـ CSS" ← "أضف JavaScript"\n\n3. **Pomodoro Technique**\n   - 25 دقيقة شغل + 5 دقيقة راحة\n   - بعد 4 دورات خذ 15-30 دقيقة راحة\n   - استخدم: Tomatotimer أو Forest\n\n4. **قاعدة 80/20**\n   - 80% من النتائج من 20% من الجهد\n   - ركز على المهم: أكتب كود مش أعدل الـ Colors\n\n5. **أبعد المشتتات**\n   - الموبايل في أوضة تانية\n   - استخدم Cold Turkey لحظر المواقع\n\n6. **كافئ نفسك**\n   - بعد ما تخلص مهمة كبيرة، خد break\n   - شوف حلقة، العب، اخرج\n\nالأهم: ابدأ — أكتر حاجة صعبة هي أول 5 دقايق' },
  { category_id: 6, title: 'اي الفرق بين الـ RAM و الـ ROM و التخزين؟', body: 'كثير يخلط بينهم.\n\n**RAM (Random Access Memory)**\n- ذاكرة مؤقتة\n- بتتسحل لما تقفل الجهاز\n- المسؤولة عن سرعة تعدد المهام\n- مثال: 8GB, 16GB, 32GB\n- كل ما كبرت، كل ما قدرت تفتح برامج أكثر\n\n**ROM (Read Only Memory)**\n- ذاكرة دائمة للقراءة فقط\n- فيها BIOS/UEFI — الكود اللي يشغل الجهاز\n- مش بتتغير\n\n**التخزين (Storage)**\n- هارد ديسك أو SSD\n- البيانات بتفضل حتى لو قفلت الجهاز\n- مثال: 256GB, 512GB, 1TB\n- هنا بتحفظ: صور، ملفات، برامج، ألعاب\n\n**الخلاصة:**\n- RAM = المساحة اللي تشتغل عليها دلوقتي\n- ROM = التعليمات الأساسية للجهاز\n- Storage = المكان اللي تحفظ فيه حاجتك\n\nللمستخدم العادي: 8GB RAM + 256GB SSD كافية' },
]

async function main() {
  console.log('بدء زرع البيانات...')

  for (let i = 0; i < seeds.length; i++) {
    const seed = seeds[i]
    const slug = seed.title
      .replace(/[^\w\s\u0600-\u06FF]/g, '')
      .replace(/\s+/g, '-')
      .toLowerCase()
      .slice(0, 80) + '-' + Date.now() + '-' + i

    const { error } = await supabase
      .from('threads')
      .insert({
        category_id: seed.category_id,
        author_id: null, // Will be set by trigger
        title: seed.title,
        slug,
        body: seed.body,
        status: 'published',
        views: Math.floor(Math.random() * 500) + 50,
      })

    if (error) {
      console.error(`خطأ في الموضوع ${i + 1}: ${seed.title.slice(0, 30)}...`, error.message)
    } else {
      console.log(`✅ ${i + 1}/${seeds.length}: ${seed.title.slice(0, 40)}...`)
    }
  }

  console.log('تم الانتهاء من زرع البيانات!')
}

main().catch(console.error)
